// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqvtp0IWvJFQgbVuj4NsSgQQDVtvwD1tY',
    appId: '1:808473473804:web:2c7cf4c307f3a3d1a78f29',
    messagingSenderId: '808473473804',
    projectId: 'the-tumaric-indian-cusine',
    authDomain: 'the-tumaric-indian-cusine.firebaseapp.com',
    storageBucket: 'the-tumaric-indian-cusine.firebasestorage.app',
    measurementId: 'G-S35W1JTW9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqZjSgAuSdPP6Ww5YqekR7Ip1bM6j9waI',
    appId: '1:808473473804:android:71afc6e0f49bc3d7a78f29',
    messagingSenderId: '808473473804',
    projectId: 'the-tumaric-indian-cusine',
    storageBucket: 'the-tumaric-indian-cusine.firebasestorage.app',
  );
}
